language: "python"

python:
  - "2.7"

install:
  - pip install --upgrade pip
  - pip install -e .[PIL]
  - python setup.py install

bundler_args: --retry 3

script: "python -m unittest discover tests"