language: "python"

python:
  - "2.7"

install:
  - pip install --upgrade pip
  - pip install -e .[PIL]
  - pip install coveralls

bundler_args: --retry 3

env:
  - TRAVIS=1

script:
  - coverage run --source . -m unittest discover tests
  - coveralls